try {
    println("try");
} catch (e) {
    println("catch");
} finally {
    error("IN FINALLY");
}